spring:
  application:
    name: sfg-pet-clinic
  profiles:
    active: springdatajpa
  messages:
    basename: messages/messages
  banner:
    image:
      location: avengersLogo.jpg
  docker:
    compose:
      enabled: false
      stop:
        command: down  
          
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always             
